# Q1

In [5]:
def tree_ref(tree , t):
    ans=()
    nt=tree
    for level in t:
        nt=nt[level]
    return nt

In [6]:
tree=(((1, 2), 3), (4, (5, 6)), 7, (8, 9, 10))
print(tree_ref(tree,(0,)))

((1, 2), 3)


In [7]:
print(tree_ref(tree,(1,1,1)))

6


In [8]:
print(tree_ref(tree,(1,1)))

(5, 6)


In [10]:
print(tree_ref(tree,()))

(((1, 2), 3), (4, (5, 6)), 7, (8, 9, 10))


# Q3

In [12]:
graph = {
  'A' : ['B','C'],
  'B' : ['D', 'E'],
  'C' : ['F'],
  'D' : [],
  'E' : ['F'],
  'F' : []
}

visited = [] # List to keep track of visited nodes.
queue = []     #Initialize a queue

def bfs(visited, graph, node):
    queue.append(node)
    visited.append(node)
    while(queue):
        cur=queue.pop(0)
        print(cur)
        for x in graph[cur]:
            if x not in visited:
                queue.append(x)
                visited.append(x)
                
bfs(visited,graph,'A')

A
B
C
D
E
F


# Q4

In [15]:
from collections import deque
graph = {
  'A' : ['B','C'],
  'B' : ['D', 'E'],
  'C' : ['F'],
  'D' : [],
  'E' : ['F'],
  'F' : []
}

visited = set()

def dfs(visited, graph, node):
    if node not in visited:
        visited.add(node)
        print(node)
        for x in graph[node]:
            dfs(visited,graph,x)

dfs(visited,graph,'A')

A
B
D
E
F
C


# Q5

In [26]:
def ucs_weight(from_node, to_node, weights=None): #We can supply the weights to the graph
    return weights.get((from_node, to_node), 10e100) if weights else 1

def ucs(graph, start, end, weights=None):
    frontier = PriorityQueue()
    frontier.put((0, start))  # (priority, node)
    explored = []

    while True:
        if frontier.empty():
            print("No way Exception")

        ucs_w, current_node = frontier.get()
        explored.append(current_node)
        print(current_node)

        if current_node == end:
            return

        for node in graph[current_node]:
            if node not in explored:
                frontier.put((
                    ucs_w + ucs_weight(current_node, node, weights),
                    node
                ))
ucs(graph,'A','F')

A
B
C
D
E
F


# Q6

In [27]:
from collections import defaultdict 

class Graph: 

    def __init__(self,vertices): 
        self.V = vertices 
        self.graph = defaultdict(list) 

    def addEdge(self,u,v): 
        self.graph[u].append(v) 

    def DLS(self,src,target,maxDepth): 
        if src == target : return True
        if maxDepth <= 0 : return False

        for i in self.graph[src]: 
                if(self.DLS(i,target,maxDepth-1)): 
                    return True
        return False

    def IDDFS(self,src, target, maxDepth): 

        for i in range(maxDepth): 
            if (self.DLS(src, target, i)): 
                return True
        return False

g = Graph (7); 
g.addEdge(0, 1) 
g.addEdge(0, 2) 
g.addEdge(1, 3) 
g.addEdge(1, 4) 
g.addEdge(2, 5) 
g.addEdge(2, 6) 

target = 6; maxDepth = 3; src = 0

if g.IDDFS(src, target, maxDepth) == True: 
    print ("Target is reachable from source " +
        "within max depth") 
else : 
    print ("Target is NOT reachable from source " +
        "within max depth")

Target is reachable from source within max depth


# Q7

In [15]:
import numpy as np
import os
class Node:
    def __init__(self, node_no, data, parent, act, cost):
        self.data = data
        self.parent = parent
        self.act = act
        self.node_no = node_no
        self.cost = cost

def get_initial():
    print("Please enter number from 0-8, no number should be repeated or be out of this range")
    initial_state = np.zeros(9)
    for i in range(9):
        states = int(input("Enter the " + str(i + 1) + " number: "))
        if states < 0 or states > 8:
            print("Please only enter states which are [0-8], run code again")
            exit(0)
        else:
            initial_state[i] = np.array(states)
    return np.reshape(initial_state, (3, 3))


def find_index(puzzle):
    i, j = np.where(puzzle == 0)
    i = int(i)
    j = int(j)
    return i, j


def move_left(data):
    i, j = find_index(data)
    if j == 0:
        return None
    else:
        temp_arr = np.copy(data)
        temp = temp_arr[i, j - 1]
        temp_arr[i, j] = temp
        temp_arr[i, j - 1] = 0
        return temp_arr


def move_right(data):
    i, j = find_index(data)
    if j == 2:
        return None
    else:
        temp_arr = np.copy(data)
        temp = temp_arr[i, j + 1]
        temp_arr[i, j] = temp
        temp_arr[i, j + 1] = 0
        return temp_arr


def move_up(data):
    i, j = find_index(data)
    if i == 0:
        return None
    else:
        temp_arr = np.copy(data)
        temp = temp_arr[i - 1, j]
        temp_arr[i, j] = temp
        temp_arr[i - 1, j] = 0
        return temp_arr


def move_down(data):
    i, j = find_index(data)
    if i == 2:
        return None
    else:
        temp_arr = np.copy(data)
        temp = temp_arr[i + 1, j]
        temp_arr[i, j] = temp
        temp_arr[i + 1, j] = 0
        return temp_arr


def move_tile(action, data):
    if action == 'up':
        return move_up(data)
    if action == 'down':
        return move_down(data)
    if action == 'left':
        return move_left(data)
    if action == 'right':
        return move_right(data)
    else:
        return None


def print_states(list_final):
    print("printing final solution")
    for l in list_final:
        print("Move : " + str(l.act) + "\n" + "Result : " + "\n" + str(l.data) + "\t" + "node number:" + str(l.node_no))


def write_path(path_formed):
    if os.path.exists("Path_file.txt"):
        os.remove("Path_file.txt")

    f = open("Path_file.txt", "a")
    for node in path_formed:
        if node.parent is not None:
            f.write(str(node.node_no) + "\t" + str(node.parent.node_no) + "\t" + str(node.cost) + "\n")
    f.close()


def write_node_explored(explored):  # To write all the nodes explored by the program
    if os.path.exists("Nodes.txt"):
        os.remove("Nodes.txt")

    f = open("Nodes.txt", "a")
    for element in explored:
        f.write('[')
        for i in range(len(element)):
            for j in range(len(element)):
                f.write(str(element[j][i]) + " ")
        f.write(']')
        f.write("\n")
    f.close()


def write_node_info(visited):  # To write all the info about the nodes explored by the program
    if os.path.exists("Node_info.txt"):
        os.remove("Node_info.txt")

    f = open("Node_info.txt", "a")
    for n in visited:
        if n.parent is not None:
            f.write(str(n.node_no) + "\t" + str(n.parent.node_no) + "\t" + str(n.cost) + "\n")
    f.close()


def path(node):  # To find the path from the goal node to the starting node
    p = []  # Empty list
    p.append(node)
    parent_node = node.parent
    while parent_node is not None:
        p.append(parent_node)
        parent_node = parent_node.parent
    return list(reversed(p))


def exploring_nodes(node):
    print("Exploring Nodes")
    actions = ["down", "up", "left", "right"]
    goal_node = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
    node_q = [node]
    final_nodes = []
    visited = []
    final_nodes.append(node_q[0].data.tolist())  # Only writing data of nodes in seen
    node_counter = 0  # To define a unique ID to all the nodes formed

    while node_q:
        current_root = node_q.pop(0)  # Pop the element 0 from the list
        if current_root.data.tolist() == goal_node.tolist():
            print("Goal reached")
            return current_root, final_nodes, visited

        for move in actions:
            temp_data = move_tile(move, current_root.data)
            if temp_data is not None:
                node_counter += 1
                child_node = Node(node_counter, np.array(temp_data), current_root, move, 0)  # Create a child node

                if child_node.data.tolist() not in final_nodes:  # Add the child node data in final node list
                    node_q.append(child_node)
                    final_nodes.append(child_node.data.tolist())
                    visited.append(child_node)
                    if child_node.data.tolist() == goal_node.tolist():
                        print("Goal_reached")
                        return child_node, final_nodes, visited
    return None, None, None  # return statement if the goal node is not reached


def check_correct_input(l):
    array = np.reshape(l, 9)
    for i in range(9):
        counter_appear = 0
        f = array[i]
        for j in range(9):
            if f == array[j]:
                counter_appear += 1
        if counter_appear >= 2:
            print("invalid input, same number entered 2 times")
            exit(0)


def check_solvable(g):
    arr = np.reshape(g, 9)
    counter_states = 0
    for i in range(9):
        if not arr[i] == 0:
            check_elem = arr[i]
            for x in range(i + 1, 9):
                if check_elem < arr[x] or arr[x] == 0:
                    continue
                else:
                    counter_states += 1
    if counter_states % 2 == 0:
        print("The puzzle is solvable, generating path")
    else:
        print("The puzzle is insolvable, still creating nodes")


# Final Running of the Code

# uncomment the line below to run it for a fixed data input and comment the line below it
# k = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
k = get_initial()

check_correct_input(k)
check_solvable(k)

root = Node(0, k, None, None, 0)

# BFS implementation call
goal, s, v = exploring_nodes(root)

if goal is None and s is None and v is None:
    print("Goal State could not be reached, Sorry")
else:
    # Print and write the final output
    print_states(path(goal))
    write_path(path(goal))
    write_node_explored(s)
    write_node_info(v)


Please enter number from 0-8, no number should be repeated or be out of this range
Enter the 1 number: 4
Enter the 2 number: 5
Enter the 3 number: 6
Enter the 4 number: 7
Enter the 5 number: 1
Enter the 6 number: 2
Enter the 7 number: 3
Enter the 8 number: 8
Enter the 9 number: 0
The puzzle is solvable, generating path
Exploring Nodes
Goal_reached
printing final solution
Move : None
Result : 
[[4. 5. 6.]
 [7. 1. 2.]
 [3. 8. 0.]]	node number:0
Move : left
Result : 
[[4. 5. 6.]
 [7. 1. 2.]
 [3. 0. 8.]]	node number:2
Move : left
Result : 
[[4. 5. 6.]
 [7. 1. 2.]
 [0. 3. 8.]]	node number:7
Move : up
Result : 
[[4. 5. 6.]
 [0. 1. 2.]
 [7. 3. 8.]]	node number:19
Move : up
Result : 
[[0. 5. 6.]
 [4. 1. 2.]
 [7. 3. 8.]]	node number:43
Move : right
Result : 
[[5. 0. 6.]
 [4. 1. 2.]
 [7. 3. 8.]]	node number:76
Move : down
Result : 
[[5. 1. 6.]
 [4. 0. 2.]
 [7. 3. 8.]]	node number:129
Move : down
Result : 
[[5. 1. 6.]
 [4. 3. 2.]
 [7. 0. 8.]]	node number:227
Move : left
Result : 
[[5. 1. 6.]
 [4.

##### Q8

In [10]:
from collections import deque
 
def BFS(a, b, target):
    m = {} 
    isSolvable = False
    path = []
    q = deque()
    q.append((0, 0))
    while (len(q) > 0):
        u = q.popleft() 
        if ((u[0], u[1]) in m):
            continue
        if ((u[0] > a or u[1] > b or
             u[0] < 0 or u[1] < 0)):
            continue
        path.append([u[0], u[1]])
        m[(u[0], u[1])] = 1
        if (u[0] == target or u[1] == target):
            isSolvable = True
            if (u[0] == target):
                if (u[1] != 0):
                    path.append([u[0], 0])
            else:
                if (u[0] != 0):
                    path.append([0, u[1]])
            for i in range(len(path)):
                print("(",path[i][0],",",path[i][1],")")
            break
        q.append([u[0], b])
        q.append([a, u[1]]) 
        for ap in range(max(a, b) + 1):
            c = u[0] + ap
            d = u[1] - ap
 
            if (c == a or (d == 0 and d >= 0)):
                q.append([c, d])
 
            c = u[0] - ap
            d = u[1] + ap
 
            if ((c == 0 and c >= 0) or d == b):
                q.append([c, d])
         
        q.append([a, 0])
        q.append([0, b]) 
 
    if (not isSolvable):
        print ("No solution")

if __name__ == '__main__':
    Jug1, Jug2, target = 4, 3, 2
    print("Solution :")
    BFS(Jug1, Jug2, target)

Solution :
( 0 , 0 )
( 0 , 3 )
( 4 , 0 )
( 4 , 3 )
( 3 , 0 )
( 1 , 3 )
( 3 , 3 )
( 4 , 2 )
( 0 , 2 )
